name       : librsync
version    : 2.0.0
release    : 1
source     :
    - https://github.com/librsync/librsync/archive/v2.0.0.tar.gz : b5c4dd114289832039397789e42d4ff0d1108ada89ce74f1999398593fae2169
license    : LGPL-2.1
summary    : librsync
description: |
    librsync is a library for calculating and applying network deltas, with an interface designed to ease integration into diverse network applications.
    librsync encapsulates the core algorithms of the rsync protocol, which help with efficient calculation of the differences between two files. The rsync algorithm is different from most differencing algorithms because it does not require the presence of the two files to calculate the delta. Instead, it requires a set of checksums of each block of one file, which together form a signature for that file. Blocks at any in the other file which have the same checksum are likely to be identical, and whatever remains is the difference.
    This algorithm transfers the differences between two files without needing both files on the same system.
    librsync is for building other programs that transfer files as efficiently as rsync. You can use librsync in a program you write to do backups, distribute binary patches to programs, or sync directories to a server or between peers.
    This tree also produces the rdiff command-line tool that exposes the key operations of librsync: generating file signatures, generating the delta from a signature to a new file, and applying the delta to regenerate the new file given the old file.
    librsync was originally written for the rproxy experiment in delta-compression for HTTP. librsync is used by: Dropbox, rdiff-backup, Duplicity, and others. (If you would like to be listed here, let me know.)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
