name       : librsync
version    : 2.0.2
release    : 3
source     :
    - https://github.com/librsync/librsync/archive/v2.0.2.tar.gz : e67b9520ee84f7239be6e948795803bd95495091cc00bf6d0e8c6976032a4af1
license    : LGPL-2.1
component  : programming.library
summary    : librsync is a library for calculating and applying network deltas, with
    an interface designed to ease integration into diverse network applications
description: |
    librsync implements the "rsync" algorithm, which allows remote differencing of binary files. librsync computes a delta relative to a file's checksum, so the two files need not both be present to generate a delta.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
